"""scientific_report — render a scientific result spec into a sophisticated HTML report.

A small library + CLI that consumes a JSON spec describing a scientific run
(metadata, hero, sections, plots, tables, explainer, glossary, references)
and emits a single self-contained HTML file in one of several "theme" styles.

Themes are deliberately distinct so that adjacent reports do not look
generated by the same template:

  - "broadsheet"  — warm cream policy-journal aesthetic (DM Serif Display +
                    Source Serif 4 + IBM Plex Mono; navy / red / mustard).
  - "editorial"   — dark editorial folio aesthetic (Fraunces + Newsreader +
                    JetBrains Mono; ink-blue / cream / rust).  Reserved for
                    future re-skinning of the SYK report.

The renderer never consumes raw simulation outputs directly — it consumes a
typed JSON spec.  The expectation is that each tutorial supplies an
exporter that converts its native artifacts (R .rds, Python .npz, etc.)
into the spec shape, then invokes the renderer.
"""
from .render import render_report, render_to_string

__all__ = ["render_report", "render_to_string"]
__version__ = "0.1.0"
